### ISSUE TITLE
자동차 기능

### ISSUE THREAD

**Issue by Hyyena** [Hyyena/woowacourse_java-racingcar-6#1]
## 1. Feature

자동차 기능

## 2. Tasks

- [ ] 자동차 이름 부여 기능
  - [x] 자동차 이름은 5자 이하
  - [ ] 자동차 이름은 쉼표(`,`) 기준으로 구분
    - [ ] 유효하지 않은 자동차 이름은 예외 처리
      - [ ] 자동차 이름은 중복되지 않음
      - [x] 자동차 이름은 공백이 아님
      - [x] 자동차 이름은 null이 아님
      - [ ] 자동차 이름은 숫자가 아님
- [x] 자동차 위치 반환 기능
- [ ] 자동차 전진 기능
    - [x] `0~9` 사이의 랜덤 값이 `4` **이상**일 경우 전진
    - [x] `0~9` 사이의 랜덤 값이 `3` **이하**일 경우 멈춤

## 3. Test

- [ ] 테스트 코드 작성 여부
