### ISSUE TITLE
자동차 경주 기능

### ISSUE THREAD

**Issue by Hyyena** [Hyyena/woowacourse_java-racingcar-6#2]
## 1. Feature

자동차 경주 기능

## 2. Tasks

- [x] 경주에 참가할 자동차 설정 기능
- [x] 경주 진행 기능
- [x] 우승자 결정 기능
  - [ ] 우승자는 한 명 이상일 수 있음
