### ISSUE TITLE
게임 기능

### ISSUE THREAD

**Issue by Hyyena** [Hyyena/woowacourse_java-racingcar-6#3]
## 1. Feature

게임 기능

## 2. Tasks

- [x] 게임 진행 기능
- [ ] 게임 초기화 기능
- [x] 게임에 참가한 자동차 목록 반환 기능
- [x] 게임 우승자 반환 기능
