### ISSUE TITLE
입력 기능

### ISSUE THREAD

**Issue by Hyyena** [Hyyena/woowacourse_java-racingcar-6#4]
## 1. Feature

입력 기능

## 2. Tasks

- [x] 자동차 이름들을 입력받는 기능
  - [x] 자동차 이름들은 쉼표(`,`)로 구분 
- [x] 경주 시도 횟수를 입력받는 기능
