### ISSUE TITLE
출력 기능

### ISSUE THREAD

**Issue by Hyyena** [Hyyena/woowacourse_java-racingcar-6#5]
## 1. Feature

출력 기능

## 2. Tasks

- [x] 시도 횟수 별로 자동차들의 위치를 출력하는 기능
- [x] 우승자를 출력하는 기능
  - [x] 우승자가 여러 명일 경우 쉼표(`,`)를 이용하여 구분
